language: python

script: python manage.py

before-install:
  - pip install -r requirements.txt

script:
  - flake8 .
  - black .
#  - coverage run --source=home manage.py test home

after_success:
  - coveralls